#### Test 1 - Re-ID

There's some unrest in the minion ranks: minions with ID numbers like "1", "42", and other "good" numbers have been lording it over the poor minions who are stuck with more boring IDs. To quell the unrest, Commander Lambda has tasked you with reassigning everyone new, random IDs based on her Completely Foolproof Scheme. 

She's concatenated the prime numbers in a single long string: "2357111317192329...". Now every minion must draw a number from a hat. That number is the starting index in that string of primes, and the minion's new ID number will be the next five digits in the string. So if a minion draws "3", their ID number will be "71113". 

Help the Commander assign these IDs by writing a function answer(n) which takes in the starting index n of Lambda's string of all primes, and returns the next five digits in the string. Commander Lambda has a lot of minions, so the value of n will always be between 0 and 10000.


##### Test cases

Inputs: (int) n = 0 -->
Output: (string) "23571"

Inputs: (int) n = 3 -->
Output: (string) "71113"

In [32]:
def answer(n):
    # According to this site https://primes.utm.edu/howmany.html there are 1229 primes below 10000
    # Therefore, with simple arithmetic I can approximately calculate that
    # In order to have a string of primes long 10005 from which to draw minions' ID,
    # I need to generate all primes in the range (2 - 21000)

    def generate_prime_numbers_list():
        # Create an empty list to hold the prime numbers
        prime_list = []

        # Starting value for the prime numbers string
        loop = 2
        
        # The range for finding prime numbers is 2 - 21000 (from https://primes.utm.edu/howmany.html)
        max_prime_range = 21000
    
        while loop < max_prime_range:
            isPrime = True

            for x in range(2, int(math.sqrt(loop) + 1)):
                if loop % x == 0: 
                    isPrime = False
                    break

            if isPrime == True:
                prime_list.append(loop)

            loop += 1

        return prime_list
    
    # Create a string from the list of prime numbers
    prime_numbers = generate_prime_numbers_list()
    prime_numbers.sort()
    prime_numbers_string = "".join(str(x) for x in prime_numbers)

    # Return the minion ID based on the starting index from Commander Lambda
    return prime_numbers_string[n:(n + 5)]

answer(10000)


'02192'

In [27]:
#########
# This is a much slower implementation of the same algorithm. It works, but many times slower.
#########

def answer(n):
    # According to this site https://primes.utm.edu/howmany.html there are 1229 primes below 10000
    # Therefore, with simple arithmetic I can approximately calculate that
    # I need to generate all primes in the range 2 - 21000
    # in order to have a string of primes long 10005 from which to draw minions' ID

    # The range for finding prime numbers is 2 - 21000 (from https://primes.utm.edu/howmany.html)
    x = 21000
    
    # Create a function to list all prime numbers in the range [2 - (x+5)]
    def non_prime_numbers(x):
        non_prime = []

    # Test if a number is prime. If it's prime the modulo will not equal 0
    # Solution: Create a list of all non-prime numbers,
    # which are subtracted from a list of all numbers in the given range
        for p in range(2, (x + 5)):
            for i in range(2, p - 1):
                if p % i == 0:
                    non_prime.append(p)
        return set(non_prime)

    non_prime_list = non_prime_numbers(x)
    
    # Create a list with all numbers in the range [2 - (x+5)] and subtract the list with non-prime numbers from it
    all_numbers = [i for i in range(2, (x + 5))]
    prime_numbers = list(set(all_numbers) - set(non_prime_list))
    prime_numbers.sort()
    prime_numbers_string = "".join(str(x) for x in prime_numbers)

    # Return the minion ID based on the starting index from Commander Lambda
    return prime_numbers_string[n:(n + 5)]

answer(0)

'23571'

#### Test 2 - Hey, I Already Did That!

Commander Lambda uses an automated algorithm to assign minions randomly to tasks, in order to keep her minions on their toes. But you've noticed a flaw in the algorithm - it eventually loops back on itself, so that instead of assigning new minions as it iterates, it gets stuck in a cycle of values so that the same minions end up doing the same tasks over and over again. You think proving this to Commander Lambda will help you make a case for your next promotion. 

You have worked out that the algorithm has the following process: 

1) Start with a random minion ID n, which is a nonnegative integer of length k in base b
2) Define x and y as integers of length k.  x has the digits of n in descending order, and y has the digits of n in ascending order
3) Define z = x - y.  Add leading zeros to z to maintain length k if necessary
4) Assign n = z to get the next minion ID, and go back to step 2

For example, given minion ID n = 1211, k = 4, b = 10, then x = 2111, y = 1112 and z = 2111 - 1112 = 0999. Then the next minion ID will be n = 0999 and the algorithm iterates again: x = 9990, y = 0999 and z = 9990 - 0999 = 8991, and so on.

Depending on the values of n, k (derived from n), and b, at some point the algorithm reaches a cycle, such as by reaching a constant value. For example, starting with n = 210022, k = 6, b = 3, the algorithm will reach the cycle of values [210111, 122221, 102212] and it will stay in this cycle no matter how many times it continues iterating. Starting with n = 1211, the routine will reach the integer 6174, and since 7641 - 1467 is 6174, it will stay as that value no matter how many times it iterates.

Given a minion ID as a string n representing a nonnegative integer of length k in base b, where 2 <= k <= 9 and 2 <= b <= 10, write a function answer(n, b) which returns the length of the ending cycle of the algorithm above starting with n. For instance, in the example above, answer(210022, 3) would return 3, since iterating on 102212 would return to 210111 when done in base 3. If the algorithm reaches a constant, such as 0, then the length is 1.

##### Test cases

Inputs: (string) n = "1211"; (int) b = 10 -->
Output:
    (int) 1

Inputs: (string) n = "210022"; (int) b = 3 -->
Output:
    (int) 3

In [9]:
def convertToBase(num,base):
    q = num / base
    r = num % base
    if (q == 0):
        return str(r)
    else:
        return convertToBase(q, base) + str(r)

pix = [210022] #the list of numbers you want converted to base b

print [convertToBase(x, 3) for x in pix]

['101200002121']


Level 2: Challenge 1 - Bunny Prisoner Locating
=======================

Keeping track of Commander Lambda's many bunny prisoners is starting to get tricky. You've been tasked with writing a program to match bunny prisoner IDs to cell locations.

The LAMBCHOP doomsday device takes up much of the interior of Commander Lambda's space station, and as a result the prison blocks have an unusual layout. They are stacked in a triangular shape, and the bunny prisoners are given numerical IDs starting from the corner, as follows:

| 7
| 4 8
| 2 5 9
| 1 3 6 10

Each cell can be represented as points (x, y), with x being the distance from the vertical wall, and y being the height from the ground. 

For example, the bunny prisoner at (1, 1) has ID 1, the bunny prisoner at (3, 2) has ID 9, and the bunny prisoner at (2,3) has ID 8. This pattern of numbering continues indefinitely (Commander Lambda has been taking a LOT of prisoners). 

Write a function answer(x, y) which returns the prisoner ID of the bunny at location (x, y). Each value of x and y will be at least 1 and no greater than 100,000. Since the prisoner ID can be very large, return your answer as a string representation of the number.

Level 2: Challenge 2 - En Route Salute
===============

Commander Lambda loves efficiency and hates anything that wastes time. She's a busy lamb, after all! She generously rewards henchmen who identify sources of inefficiency and come up with ways to remove them. You've spotted one such source, and you think solving it will help you build the reputation you need to get promoted.

Every time the Commander's employees pass each other in the hall, each of them must stop and salute each other - one at a time - before resuming their path. A salute is five seconds long, so each exchange of salutes takes a full ten seconds (Commander Lambda's salute is a bit, er, involved). You think that by removing the salute requirement, you could save several collective hours of employee time per day. But first, you need to show her how bad the problem really is.

Write a program that counts how many salutes are exchanged during a typical walk along a hallway. The hall is represented by a string. For example:
"--->-><-><-->-"

Each hallway string will contain three different types of characters: '>', an employee walking to the right; '<', an employee walking to the left; and '-', an empty space. Every employee walks at the same speed either to right or to the left, according to their direction. Whenever two employees cross, each of them salutes the other. They then continue walking until they reach the end, finally leaving the hallway. In the above example, they salute 10 times.

Write a function answer(s) which takes a string representing employees walking along a hallway and returns the number of times the employees will salute. s will contain at least 1 and at most 100 characters, each one of -, >, or <.


Test cases
==========

Inputs:
    (string) s = ">----<"
Output:
    (int) 2

Inputs:
    (string) s = "<<>><"
Output:
    (int) 4

In [68]:
def answer(s):
    # En Route Salute
    # This function returns the number of times the employees walking down a hallway will salute
    
    # Import string library
    import re

    # Remove (non-essential) dashes from the string
    strip_dashes = re.sub('-', '', s)

    # Find the location of all employees walking to the left
    left_loc = [m.start() for m in re.finditer('<', strip_dashes)]

    # Count the salutes
    return sum([(left_loc[x] - x) * 2 for x in range(0, len(left_loc))])


In [70]:
answer("<<>><")

4

In [63]:
# Matrix operations

import numpy as np

m = np.array([[[1., 2.],
               [3., 4.]]])

a = np.array([[[8., 67.],
               [3., 23.],
               [234., 235.]]])

# Inverse of a matrix
m_inv = np.linalg.inv(m)

# Create identity matrix
eye = np.identity(2)

# Matrix multiplication
m_multiply = np.dot(eye, m)
d = np.dot(a, m)

# Transpose a matrix
m_transpose = m.transpose()

print m
print a
print m_inv
print eye
print m_multiply
print m_transpose
d


[[[ 1.  2.]
  [ 3.  4.]]]
[[[   8.   67.]
  [   3.   23.]
  [ 234.  235.]]]
[[[-2.   1. ]
  [ 1.5 -0.5]]]
[[ 1.  0.]
 [ 0.  1.]]
[[[ 1.  2.]]

 [[ 3.  4.]]]
[[[ 1.]
  [ 3.]]

 [[ 2.]
  [ 4.]]]


array([[[[  209.,   284.]],

        [[   72.,    98.]],

        [[  939.,  1408.]]]])